"""DEXA ingestion, analysis, charting, and report generation."""

from .calculations import (
    DexaAnalysis,
    add_interval_efficiency,
    analyze_body_composition,
    fit_lean_mass_trend,
    modeled_body_fat_pct,
)
from .forecast import (
    AssumptionSensitivity,
    BulkCeilingForecast,
    BulkInterval,
    ForecastAssumptions,
    JackknifeSensitivity,
    PlanningInputs,
    PlanningOutlook,
    PredictiveFold,
    PredictiveScore,
    WeightEstimate,
    build_planning_outlook,
    constant_ffm_ceiling_lb,
    crossing_weight_lb,
    extract_bulk_intervals,
    forecast_bulk_ceiling,
    group_intervals_into_blocks,
    leave_one_bulk_out_score,
    probability_curve_frame,
    probability_under_target,
    safety_ceiling_lb,
    simulate_body_fat_readings,
    simulate_crossing_weights,
    smoothed_bodyweight_lb,
)
from .forecast_pipeline import ForecastOutputs, run_forecast_report
from .muscle_gain import (
    ChangeWindow,
    MuscleGainAssumptions,
    MuscleGainEstimate,
    RegionalSensitivity,
    StrengthComparison,
    TrainingEvidence,
    estimate_muscle_gain,
    leave_one_scan_out_adjusted_gains,
    summarize_training_evidence,
)
from .muscle_gain_pipeline import MuscleGainOutputs, run_muscle_gain_report
from .pipeline import ReportOutputs, run_report

__all__ = [
    "AssumptionSensitivity",
    "BulkCeilingForecast",
    "BulkInterval",
    "ChangeWindow",
    "DexaAnalysis",
    "ForecastAssumptions",
    "ForecastOutputs",
    "JackknifeSensitivity",
    "MuscleGainAssumptions",
    "MuscleGainEstimate",
    "MuscleGainOutputs",
    "PlanningInputs",
    "PlanningOutlook",
    "PredictiveFold",
    "PredictiveScore",
    "RegionalSensitivity",
    "ReportOutputs",
    "StrengthComparison",
    "TrainingEvidence",
    "WeightEstimate",
    "build_planning_outlook",
    "add_interval_efficiency",
    "analyze_body_composition",
    "constant_ffm_ceiling_lb",
    "crossing_weight_lb",
    "extract_bulk_intervals",
    "estimate_muscle_gain",
    "fit_lean_mass_trend",
    "forecast_bulk_ceiling",
    "group_intervals_into_blocks",
    "leave_one_bulk_out_score",
    "leave_one_scan_out_adjusted_gains",
    "modeled_body_fat_pct",
    "probability_curve_frame",
    "probability_under_target",
    "run_forecast_report",
    "run_muscle_gain_report",
    "run_report",
    "safety_ceiling_lb",
    "simulate_body_fat_readings",
    "simulate_crossing_weights",
    "smoothed_bodyweight_lb",
    "summarize_training_evidence",
]
